version: "3"

services:
  oracle-compose:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      ORACLE_DISABLE_ASYNCH_IO: 'true'
    ports:
      - 1521:1521
    container_name: oracle-container
